# Generated by Django 5.2.10 on 2026-09-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_workflowchatsession_workflowchatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowchatsession',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkflowChatMessage',
        ),
        migrations.DeleteModel(
            name='WorkflowChatSession',
        ),
    ]
