# Generated by Django 5.2.10 on 2026-09-27 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workflowchatsession_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='pipeline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipelines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='model',
            field=models.CharField(help_text='Model id, validated against the provider catalogue on write.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='prompt',
            field=models.TextField(help_text='Prompt template for this step. Use {input} as the placeholder.'),
        ),
        migrations.AddConstraint(
            model_name='pipelinestep',
            constraint=models.UniqueConstraint(fields=('pipeline', 'order'), name='unique_step_order_per_pipeline'),
        ),
    ]
