# Generated by Django 5.2.10 on 2026-09-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pipelinestep_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestep',
            name='is_output',
            field=models.BooleanField(default=False, help_text="Show this step's result as a pipeline output."),
        ),
        migrations.AddField(
            model_name='pipelinestep',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Short name shown in the UI.', max_length=100),
        ),
    ]
